### ISSUE TITLE
登录必现崩溃

### ISSUE THREAD

**Issue by TchaikovDriver** [ibroadlink/APPSDK_Android_Demo#2]
崩溃日志
```
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
    Process: com.broadlink.blappsdkdemo, PID: 21069
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NoSuchMethodError: No virtual method setLid(Ljava/lang/String;)V in class Lcn/com/broadlink/base/BLLoginResult; or its super classes (declaration of 'cn.com.broadlink.base.BLLoginResult' appears in /data/app/com.broadlink.blappsdkdemo-BfsMfScldB9-25InzvbJ5A==/split_lib_dependencies_apk.apk)
        at cn.com.broadlink.account.c.a(Unknown Source:310)
        at cn.com.broadlink.account.BLAccount.fastLogin(Unknown Source:92)
        at cn.com.broadlink.blappsdkdemo.activity.account.AccountVerifyCodeLoginActivity$FastLoginTask.doInBackground(AccountVerifyCodeLoginActivity.java:168)
        at cn.com.broadlink.blappsdkdemo.activity.account.AccountVerifyCodeLoginActivity$FastLoginTask.doInBackground(AccountVerifyCodeLoginActivity.java:152)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```
机型：一加7Pro Android Pie

**Comment by echojiangyq** [comment]
> 崩溃日志
> 
> ```
> E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
>     Process: com.broadlink.blappsdkdemo, PID: 21069
>     java.lang.RuntimeException: An error occurred while executing doInBackground()
>         at android.os.AsyncTask$3.done(AsyncTask.java:354)
>         at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
>         at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:271)
>         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:764)
>      Caused by: java.lang.NoSuchMethodError: No virtual method setLid(Ljava/lang/String;)V in class Lcn/com/broadlink/base/BLLoginResult; or its super classes (declaration of 'cn.com.broadlink.base.BLLoginResult' appears in /data/app/com.broadlink.blappsdkdemo-BfsMfScldB9-25InzvbJ5A==/split_lib_dependencies_apk.apk)
>         at cn.com.broadlink.account.c.a(Unknown Source:310)
>         at cn.com.broadlink.account.BLAccount.fastLogin(Unknown Source:92)
>         at cn.com.broadlink.blappsdkdemo.activity.account.AccountVerifyCodeLoginActivity$FastLoginTask.doInBackground(AccountVerifyCodeLoginActivity.java:168)
>         at cn.com.broadlink.blappsdkdemo.activity.account.AccountVerifyCodeLoginActivity$FastLoginTask.doInBackground(AccountVerifyCodeLoginActivity.java:152)
>         at android.os.AsyncTask$2.call(AsyncTask.java:333)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
>         at java.lang.Thread.run(Thread.java:764) 
> ```
> 
> 机型：一加7Pro Android Pie

用新版本试试
